// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	COMMON: {
		/**
		 * I​n​t​e​r​n​a​l​ ​S​e​r​v​e​r​ ​E​r​r​o​r
		 */
		'500': string
	}
	AUTH: {
		/**
		 * L​o​g​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		login_success: string
	}
}

export type TranslationFunctions = {
	COMMON: {
		/**
		 * Internal Server Error
		 */
		'500': () => LocalizedString
	}
	AUTH: {
		/**
		 * Login successfully
		 */
		login_success: () => LocalizedString
	}
}

export type Formatters = {}
